### ISSUE TITLE
Feature request: Nested lists

### ISSUE THREAD

**Issue by kimisgold** [schne324/dragon-drop#7] opened 2018-01-31 16:38 UTC
My project uses drag-and-drop interfaces that are not currently accessible, and I'd love to use dragon drop to replace our current sorting jquery plugin. Many of our interfaces are for creating navigation lists, and so the ability to nest the sortable items is key.

**Comment by schne324** [comment] 2018-02-01 00:50
This sounds interesting. Could you go more in depth on how this interaction works? I would like to get a better idea of what this feature would entail.

Screenshots would be helpful too!

**Comment by itsterry** [comment] 2018-02-01 13:13
+1 for this feature

I've attached a screenshot from a project on which I'm currently working, using a tree structure to manage page position for a website's navigation

In it, the Events page has 3 child pages, called (imaginatively) Event 1, Event 2, and Event 3

I'd love to be able to drag Event 3 to above -say- Event 1 without being able to drag it into Resources (the item above Events) or Faqs (the Item below Events)

Hope it helps!
![cms](https://user-images.githubusercontent.com/96843/35680251-b6b8b94e-0751-11e8-9a09-162d0a0ab183.png)

**Comment by schne324** [comment] 2018-02-02 14:15
Ok, thanks for the explanation + screenshot.  I'll probably tag a new release including this feature this evening or tomorrow

p.s. the feature is sitting in [this branch](https://github.com/schne324/dragon-drop/tree/nested-lists). I just need to write some tests and then tag the release

**Comment by itsterry** [comment] 2018-02-03 00:53
Awesomely quick! Thank you! I'll check it out

**Comment by schne324** [comment] 2018-02-03 03:39
Support for nested lists (which turned out to be an extremely easy feature to add (~2 lines of code)) has been added in the latest release!  All you have to do is pass `nested: true` in the configuration

Please check [nested lists demo](https://schne324.github.io/dragon-drop/demo/index.html#demo-3) out.

I want to make sure this is what both of you (@itsterry @kimisgold) were talking about  before closing this issue

**Comment by schne324** [comment] 2018-02-03 03:42
False alarm...I've just realized that mouse dragging within sublists is messed up.

Hang tight and I'll update this issue when the problem is resolved

**Comment by schne324** [comment] 2018-02-03 04:24
This isn't quite resolved yet, I've added keyboard support for nested lists but not mouse support yet

**Comment by schne324** [comment] 2018-02-03 19:59
@kimisgold @itsterry version 3.2.1 [supports nested lists](https://github.com/schne324/dragon-drop#nested-boolean) there is now also a [demo](http://schne324.github.io/dragon-drop/demo/index.html#demo-3)

For now, sublists are locked (as in you can't move an item from one sublist to another but you _can_ reorder sublist items within their original list containers). From what I gathered, this is @itsterry 's desired behavior.  I do however plan on supporting the use case of moving sublist items between sublists. See #11 to track that feature.

I will close this issue if this is what both of you had in mind

**Comment by itsterry** [comment] 2018-02-03 20:01
@schne324 Awesome: this is exactly what we need. Thank you!

**Comment by schne324** [comment] 2018-02-03 20:02
No problem, the configuration needed is a little funky for now.  Once I address  #11 it should be a little more intuitive.

Cheers!

**Comment by schne324** [comment] 2018-02-07 03:06
@kimisgold is [this](http://schne324.github.io/dragon-drop/demo/index.html#demo-3) the kind of nesting you were looking for?

**Comment by kimisgold** [comment] 2018-02-07 18:09
Hi @schne324, thanks for the fast response on this! My use case is more like <a href="https://github.com/schne324/dragon-drop/issues/7#issuecomment-362849650">what you described</a>, in that I need to be able to to move items in and out of sublists. For an example, you can look at our demo sandbox: http://dev.omeka.org/omeka-s-sandbox/admin/site/s/americanart/navigation (username/password: omekasdemo1@example.com/omekasdemo1). We're currently using <a href="https://www.jstree.com/demo/">jstree</a> as our sorting tool.

**Comment by schne324** [comment] 2018-02-08 00:15
@kimisgold this feature sounds cool but may require some decent refactoring. I'll leave this ticket open until full nested lists support is added

**Comment by kimisgold** [comment] 2018-02-08 19:47
Thanks, I look forward to seeing what you do!

**Comment by schne324** [comment] 2018-02-08 23:23
closing in favor #11  which has a more descriptive title

**Closed by schne324** 2018-02-08 23:23 UTC
